<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\User;
use Illuminate\Support\Facades\Hash;

class UserSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        User::insert([
            //DOCTORS
            [
                'name'       => 'DR.AHMED',
                'email'      => 'ahemd@clinic.com',
                'password'   => Hash::make('123456'),
                'phone'      => null,
                'image'      =>'assets/images/01.jpg',
                'is_user'    => false,
                'is_admin'   => false,
                'is_doctor'  => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name'       => 'DR.MOSTAFA',
                'email'      => 'mostafa@clinic.com',
                'password'   => Hash::make('123456'),
                'phone'      => null,
                'image'      => 'assets/images/02.jpg',
                'is_user'    => false,
                'is_admin'   => false,
                'is_doctor'  => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name'       => 'DR.NOAH',
                'email'      => 'noah@clinic.com',
                'password'   => Hash::make('123456'),
                'phone'      => null,
                'image'      => 'assets/images/03.jpg',
                'is_user'    => false,
                'is_admin'   => false,
                'is_doctor'  => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name'       => 'DR.HEND',
                'email'      => 'hend@clinic.com',
                'password'   => Hash::make('123456'),
                'phone'      => null,
                'image'      => 'assets/images/04.jpg',
                'is_user'    => false,
                'is_admin'   => false,
                'is_doctor'  => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name'       => 'DR.EDWARD',
                'email'      => 'edward@clinic.com',
                'password'   => Hash::make('123456'),
                'phone'      => null,
                'image'      => 'assets/images/05.jpg',
                'is_user'    => false,
                'is_admin'   => false,
                'is_doctor'  => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name'       => 'DR.CHARLES',
                'email'      => 'charles@clinic.com',
                'password'   => Hash::make('123456'),
                'phone'      => null,
                'image'      => 'assets/images/06.jpg',
                'is_user'    => false,
                'is_admin'   => false,
                'is_doctor'  => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name'       => 'DR.JASMINE',
                'email'      => 'jasmine@clinic.com',
                'password'   => Hash::make('123456'),
                'phone'      => null,
                'image'      => 'assets/images/07.jpg',
                'is_user'    => false,
                'is_admin'   => false,
                'is_doctor'  => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name'       => 'DR.FARAH',
                'email'      => 'farah@clinic.com',
                'password'   => Hash::make('123456'),
                'phone'      => null,
                'image'      => 'assets/images/08.jpg',
                'is_user'    => false,
                'is_admin'   => false,
                'is_doctor'  => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name'       => 'DR.NADA',
                'email'      => 'nada@clinic.com',
                'password'   => Hash::make('123456'),
                'phone'      => null,
                'image'      => 'assets/images/09.jpg',
                'is_user'    => false,
                'is_admin'   => false,
                'is_doctor'  => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name'       => 'DR.REDA',
                'email'      => 'reda@clinic.com',
                'password'   => Hash::make('123456'),
                'phone'      => null,
                'image'      => 'assets/images/10.jpg',
                'is_user'    => false,
                'is_admin'   => false,
                'is_doctor'  => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name'       => 'DR.TAMER',
                'email'      => 'tamer@clinic.com',
                'password'   => Hash::make('123456'),
                'phone'      => null,
                'image'      => 'assets/images/11.jpg',
                'is_user'    => false,
                'is_admin'   => false,
                'is_doctor'  => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name'       => 'DR.JOSEPH',
                'email'      => 'joseph@clinic.com',
                'password'   => Hash::make('123456'),
                'phone'      => null,
                'image'      => 'assets/images/12.jpg',
                'is_user'    => false,
                'is_admin'   => false,
                'is_doctor'  => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            //USERS
            [
                'name'       => 'OMAR HASSAN',
                'email'      => 'omar@clinic.com',
                'password'   => Hash::make('123456'),
                'phone'      => '01000000001',
                'image'      => null,
                'is_user'    => true,
                'is_admin'   => false,
                'is_doctor'  => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name'       => 'SALMA AHMED',
                'email'      => 'salma@clinic.com',
                'password'   => Hash::make('123456'),
                'phone'      => '01000000002',
                'image'      => null,
                'is_user'    => true,
                'is_admin'   => false,
                'is_doctor'  => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name'       => 'MOHAMED ALI',
                'email'      => 'mohamed@clinic.com',
                'password'   => Hash::make('123456'),
                'phone'      => '01000000003',
                'image'      => null,
                'is_user'    => true,
                'is_admin'   => false,
                'is_doctor'  => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name'       => 'FATMA HANY',
                'email'      => 'fatma@clinic.com',
                'password'   => Hash::make('123456'),
                'phone'      => '01000000004',
                'image'      => null,
                'is_user'    => true,
                'is_admin'   => false,
                'is_doctor'  => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name'       => 'AHMED KHALED',
                'email'      => 'ahmed@clinic.com',
                'password'   => Hash::make('123456'),
                'phone'      => '01000000005',
                'image'      => null,
                'is_user'    => true,
                'is_admin'   => false,
                'is_doctor'  => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name'       => 'NOURHAN TAREK',
                'email'      => 'nourhan@clinic.com',
                'password'   => Hash::make('123456'),
                'phone'      => '01000000006',
                'image'      => null,
                'is_user'    => true,
                'is_admin'   => false,
                'is_doctor'  => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name'       => 'YASSER HOSNY',
                'email'      => 'yasser@clinic.com',
                'password'   => Hash::make('123456'),
                'phone'      => '01000000007',
                'image'      => null,
                'is_user'    => true,
                'is_admin'   => false,
                'is_doctor'  => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name'       => 'MARIAM SAMIR',
                'email'      => 'mariam@clinic.com',
                'password'   => Hash::make('123456'),
                'phone'      => '01000000008',
                'image'      => null,
                'is_user'    => true,
                'is_admin'   => false,
                'is_doctor'  => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name'       => 'HANY REDA',
                'email'      => 'hany@clinic.com',
                'password'   => Hash::make('123456'),
                'phone'      => '01000000009',
                'image'      => null,
                'is_user'    => true,
                'is_admin'   => false,
                'is_doctor'  => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name'       => 'DINA ASHRAF',
                'email'      => 'dina@clinic.com',
                'password'   => Hash::make('123456'),
                'phone'      => '01000000010',
                'image'      => null,
                'is_user'    => true,
                'is_admin'   => false,
                'is_doctor'  => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name'       => 'SAMIR LOTFY',
                'email'      => 'samir@clinic.com',
                'password'   => Hash::make('123456'),
                'phone'      => '01000000011',
                'image'      => null,
                'is_user'    => true,
                'is_admin'   => false,
                'is_doctor'  => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name'       => 'LAILA MAGDY',
                'email'      => 'laila@clinic.com',
                'password'   => Hash::make('123456'),
                'phone'      => '01000000012',
                'image'      => null,
                'is_user'    => true,
                'is_admin'   => false,
                'is_doctor'  => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name'       => 'MOSTAFA ADEL',
                'email'      => 'mostafa2@clinic.com',
                'password'   => Hash::make('123456'),
                'phone'      => '01000000013',
                'image'      => null,
                'is_user'    => true,
                'is_admin'   => false,
                'is_doctor'  => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name'       => 'HANAN KAMAL',
                'email'      => 'hanan@clinic.com',
                'password'   => Hash::make('123456'),
                'phone'      => '01000000014',
                'image'      => null,
                'is_user'    => true,
                'is_admin'   => false,
                'is_doctor'  => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name'       => 'IBRAHIM LOTFY',
                'email'      => 'ibrahim@clinic.com',
                'password'   => Hash::make('123456'),
                'phone'      => '01000000015',
                'image'      => null,
                'is_user'    => true,
                'is_admin'   => false,
                'is_doctor'  => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            //ADMIN
            [
            'name' => 'NADA SHETA',
            'email' => 'admin283@gmail.com',
            'password' => Hash::make('123456'),
            'phone'      => null,
            'image'      => null, 
            'is_admin' => true,
            'is_user' => true,
            'is_doctor' => false,
            'created_at' => now(),
            'updated_at' => now(),
            ]
        ]);
    }
}
